import{useMemo,useState}from'react';import{AlertTriangle,Car,Clock3,DollarSign,Upload,Search}from'lucide-react';
const demo=[{ro:'12471',customer:'Johnson',insurer:'State Farm',days:11,stage:'Supplement',parts:4200,total:9100,missing:0,ecd:'Today',tech:'Anthony',estimator:'Alec',labor:18.4,growth:24},{ro:'12462',customer:'Smith',insurer:'State Farm',days:8,stage:'Waiting Parts',parts:5100,total:9600,missing:1,firstSeen:'4 days',ecd:'Tomorrow',tech:'Mike',estimator:'Christian',labor:12.1,growth:8},{ro:'12488',customer:'Davis',insurer:'State Farm',days:15,stage:'Repair Complete',parts:6800,total:12100,missing:0,ecd:'Past Due',tech:'Anthony',estimator:'Tyler',labor:0,growth:6},{ro:'12490',customer:'Miller',insurer:'State Farm',days:6,stage:'Body',parts:3200,total:7400,missing:0,ecd:'3 days',tech:'Mike',estimator:'Alec',labor:22.8,growth:4}];
function risk(r){let n=0;if(r.days>14)n+=3;else if(r.days>10)n+=2;if(r.ecd==='Past Due'||r.ecd==='Today')n+=3;else if(r.ecd==='Tomorrow')n+=2;if(r.missing&&r.firstSeen)n+=3;if(r.growth>10)n+=2;if(r.stage==='Repair Complete'&&r.ecd==='Past Due')n+=2;return n>=6?'Critical':n>=3?'At Risk':'On Track'}
export function App(){const[rows]=useState(demo),[q,setQ]=useState('');const sf=useMemo(()=>rows.filter(r=>/state\s*farm/i.test(r.insurer)),[rows]);const shown=sf.filter(r=>(r.ro+r.customer+r.tech+r.estimator+r.stage).toLowerCase().includes(q.toLowerCase()));const critical=sf.filter(r=>risk(r)==='Critical').length,atRisk=sf.filter(r=>risk(r)==='At Risk').length,wip=sf.reduce((a,r)=>a+r.total,0),parts=sf.reduce((a,r)=>a+r.parts,0);
function upload(e){if(e.target.files?.[0])alert('WIP upload entry point is ready. Next we will map the actual WIP columns to replace demo rows safely.')}
return <div className="app"><aside><div className="brand">DRP<span>COMMAND</span></div><b>LIVE SHOP</b><nav><a className="active">State Farm</a><a>Missing Parts</a><a>Deliveries</a><a>Event Log</a><a>Settings</a></nav><small>Independent DRP operations tool</small></aside><main><header><div><p>STATE FARM • LIVE OPERATIONS</p><h1>Command Center</h1><span>What needs action at the shop today?</span></div><label className="upload"><Upload size={17}/> Upload WIP<input type="file" accept=".csv,.xlsx" onChange={upload}/></label></header>
<section className="cards"><Card icon={<Car/>} label="ACTIVE SF ROs" value={sf.length}/><Card icon={<DollarSign/>} label="ACTIVE SF WIP" value={'$'+wip.toLocaleString()}/><Card icon={<AlertTriangle/>} label="CRITICAL" value={critical} hot/><Card icon={<Clock3/>} label="AT RISK" value={atRisk}/><Card label="PARTS % OF WIP" value={(parts/wip*100).toFixed(1)+'%'}/></section>
<section className="panel"><div className="panelHead"><div><h2>Needs Action Today</h2><p>Prioritized from live RO risk—not historical scorecard results.</p></div><div className="search"><Search size={16}/><input placeholder="Search RO, tech, estimator..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="alerts">{sf.filter(r=>risk(r)!=='On Track').map(r=><div className={'alert '+risk(r).replace(' ','').toLowerCase()} key={r.ro}><b>RO {r.ro} • {risk(r).toUpperCase()}</b><span>{r.days} days on site • {r.stage} • ECD {r.ecd}{r.missing?' • missing part '+r.firstSeen:''}</span><em>{r.missing?'ACTION: Parts ETA/source':r.growth>10?'ACTION: Estimate review':'ACTION: Validate ECD / closeout'}</em></div>)}</div></section>
<section className="panel"><div className="panelHead"><div><h2>Active State Farm Repairs</h2><p>Daily WIP scrub with operational risk scoring.</p></div></div><div className="tableWrap"><table><thead><tr><th>RO</th><th>Customer</th><th>Days</th><th>Stage</th><th>Tech</th><th>Estimator</th><th>Parts / RO</th><th>Missing</th><th>Labor Rem.</th><th>Est. Growth</th><th>ECD</th><th>Risk</th></tr></thead><tbody>{shown.map(r=><tr key={r.ro}><td><b>{r.ro}</b></td><td>{r.customer}</td><td>{r.days}</td><td>{r.stage}</td><td>{r.tech}</td><td>{r.estimator}</td><td>{(r.parts/r.total*100).toFixed(1)}%</td><td>{r.missing?r.missing+' • '+r.firstSeen:'—'}</td><td>{r.labor.toFixed(1)}h</td><td>{r.growth}%</td><td>{r.ecd}</td><td><span className={'pill '+risk(r).replace(' ','').toLowerCase()}>{risk(r)}</span></td></tr>)}</tbody></table></div></section>
<section className="bottom"><div className="panel"><h2>Today's Risk Drivers</h2><p>Cycle time • ECD exposure • missing parts aging • estimate growth • repair complete not delivered.</p><div className="targets"><span>OE target ≤80%</span><span>RvR ≥44.5%</span><span>Estimate Difference 5–7%</span><span>Event Timeliness ≥80%</span></div></div><div className="panel"><h2>Next Data Connections</h2><p>Map the real WIP export, then connect Missing Parts First Seen history and store filtering.</p></div></section></main></div>}
function Card(p){return <div className={'card '+(p.hot?'hot':'')}><div>{p.icon}</div><small>{p.label}</small><strong>{p.value}</strong></div>}